### ISSUE TITLE
Custom Route's

### ISSUE THREAD

**Issue by dionys1705** [bolt/Sitemap#31]
Hello, 

I have one hard coded route to an /contact page. Like this:

contact:
      path: /contact
      defaults: { _controller: 'Bolt\Controllers\Frontend::template', template: 'contact' }

The above route is not shown in the Sitemap. Is there a way to add this to the sitemap?

**Comment by nlemoine** [comment]
I have the same issue. Any way to add (like we can ignore) custom routes?

**Comment by bobdenotter** [comment]
The Readme notes that if you have your own routes, you might need to add the Sitemap's routes above that, since matching goes top-down: 


> if you use the `pagebinding` in `routing.yml` (or anything similar like `/{slug}`),
you need to add the following _above_ that route:

```
sitemap:
  path: /sitemap
  defaults: { _controller: sitemap.controller:sitemap }

sitemapXml:
  path: /sitemap.xml
  defaults: { _controller: sitemap.controller:sitemapXml }
```
